# Generated by Django 4.1.3 on 2022-12-05 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ('updated_at',), 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
